import { buildGuardianReportPrompt } from '../ai/aiPromptBuilder';
import { runStudentAgentTurn } from '../agents/studentAgentOrchestrator';
import { enqueueMobileSyncItem } from '../sync/mobileSyncQueue';
import { syncPendingItems } from '../sync/studentEventSyncService';
import { syncNow } from '../sync/studentSyncService';
import type { BodyReadinessSnapshot } from '../../types/healthTypes';
import type { GuardianReport } from '../../types/reportTypes';
import type { SupportSignal } from '../../types/wellbeingTypes';

type DeliveryInput = {
  studentId: string;
  learningSummary: string;
  readiness: BodyReadinessSnapshot;
  supportSignals: SupportSignal[];
};

type DeliveryResult = {
  ok: boolean;
  report?: GuardianReport;
  aiText?: string;
  message: string;
  syncState?: 'synced' | 'pending' | 'failed';
};

function toBulletList(text: string, max = 3): string[] {
  const lines = text
    .split('\n')
    .map((line) => line.replace(/^[-*0-9.\s]+/, '').trim())
    .filter((line) => line.length > 0);
  return lines.slice(0, max);
}

function createGuardianReportFromAi(input: DeliveryInput, aiText: string): GuardianReport {
  const recommendations = toBulletList(aiText, 5);
  return {
    id: `guardian_report_${Date.now()}`,
    studentId: input.studentId,
    period: 'weekly',
    learningSummary: input.learningSummary,
    physicalReadinessSummary: input.readiness.safeSummary,
    wellbeingSafeSummary: input.supportSignals.map((signal) => signal.safeSummary).join(' ') || 'No urgent wellbeing signal this week.',
    homeRecommendations: recommendations.length > 0 ? recommendations.slice(0, 3) : [
      'Use one short check-in about difficult lessons every evening.',
      'Keep study blocks short with regular rest breaks.',
      'Support consistent sleep and hydration routine.'
    ],
    schoolRecommendations: recommendations.length > 3 ? recommendations.slice(3) : [
      'Assign one focused remedial task before harder work.',
      'Review repeated misconception patterns in next class.'
    ],
    redactedFields: ['privateReflection', 'rawChat', 'rawHealthLogs'],
    generatedAt: new Date().toISOString()
  };
}

export async function generateAndDeliverGuardianReport(input: DeliveryInput): Promise<DeliveryResult> {
  const reportContext = JSON.stringify({
    studentId: input.studentId,
    learningSummary: input.learningSummary,
    physicalReadinessSummary: input.readiness.safeSummary,
    wellbeingSignals: input.supportSignals.map((signal) => ({
      signalType: signal.signalType,
      safeSummary: signal.safeSummary,
      severity: signal.severity
    }))
  });

  const prompt = buildGuardianReportPrompt(reportContext);
  const aiResult = await runStudentAgentTurn({
    action: 'guardian_report',
    contextMode: 'report',
    prompt,
    contextText: reportContext,
    userText: 'Generate a parent-safe weekly report using only provided safe data.',
    studentId: input.studentId,
    eventId: `guardian_delivery_${Date.now()}`,
    metadata: {
      deliveryChannel: 'parent_app',
      aiProviderExpected: 'cactus_local'
    }
  });

  if (!aiResult.response.ok) {
    return {
      ok: false,
      message: `AI local generation failed: ${aiResult.response.error}`
    };
  }

  const aiText = aiResult.response.text;
  const report = createGuardianReportFromAi(input, aiText);
  const queueItem = enqueueMobileSyncItem({
    id: `sync_guardian_${Date.now()}`,
    entityType: 'guardian_report',
    entityId: report.id,
    payload: {
      channel: 'parent_app',
      report
    }
  });

  await syncNow();
  const mobileSync = await syncPendingItems();
  const savedItem = mobileSync.find((item) => item.id === queueItem.id);

  if (savedItem?.status === 'synced') {
    return {
      ok: true,
      report,
      aiText,
      message: 'Guardian report was generated by local AI and synced to parent channel.',
      syncState: 'synced'
    };
  }

  if (savedItem?.status === 'failed') {
    return {
      ok: false,
      report,
      aiText,
      message: `Report generated but sync failed: ${savedItem.lastError ?? 'unknown_error'}`,
      syncState: 'failed'
    };
  }

  return {
    ok: true,
    report,
    aiText,
    message: 'Report generated. Sync is pending backend delivery.',
    syncState: 'pending'
  };
}
